[package]
name = "panamint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbfreader = "0.15.2"
petgraph = "0.6.0"
rand = "0.8.5"
rocket = { "0.5.0-rc.2", features = ["json"] }
