name:                blick
version:             0.1.0.0
github:              "erik/blick"
license:             AGPL-3
author:              "Erik Price"
maintainer:          "example@example.com"
copyright:           "2019 Erik Price"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blick#readme>

dependencies:
- base >= 4.7 && < 5
- acid-state
- aeson
- attoparsec
- base-compat
- blaze-html
- blaze-markup
- bytestring
- containers
- directory
- http-api-data
- http-client
- http-media
- http-types
- mtl
- safecopy
- servant
- servant-client
- servant-docs
- servant-server
- string-conversions
- text
- time
- transformers
- wai
- wai-logger
- warp

library:
  source-dirs: src

executables:
  blick-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blick

tests:
  blick-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blick
