[package]
name = "fnr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grep = "0.2.8"
ignore = "0.4"
lazy_static = "1.4.0"
regex = "1.5.4"
structopt = { version = "0.3" }
